# Generated by Django 4.2.5 on 2023-09-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='owners',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
