# Generated by Django 4.2.5 on 2023-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_profession_tag_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='ToDo', max_length=255),
        ),
    ]
