# Generated by Django 4.2.5 on 2023-09-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_profession_title_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='mainapp.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sprints', to='mainapp.sprint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='BackLog', max_length=255, null=True),
        ),
    ]
