# Generated by Django 4.2.5 on 2023-09-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_sprint_project_alter_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='story_point',
            field=models.IntegerField(null=True),
        ),
    ]
