# Generated by Django 4.2.5 on 2023-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_task_priority_task_story_point_task_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
